"""Remove job_id as a primary key

Revision ID: 1e8647112b40
Revises: 5920e901bd52
Create Date: 2022-02-22 17:25:36.757012

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e8647112b40"
down_revision = "5920e901bd52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "job_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "job_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###
