"""Remove  col in Task

Revision ID: 5920e901bd52
Revises: 681ce1cc0929
Create Date: 2022-02-22 16:47:35.588000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5920e901bd52"
down_revision = "681ce1cc0929"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "complete")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
