"""Change Task ID to int

Revision ID: 681ce1cc0929
Revises: ede715e38fda
Create Date: 2022-02-22 16:33:51.340164

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "681ce1cc0929"
down_revision = "ede715e38fda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("job_id", sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "job_id")
    # ### end Alembic commands ###
