"""Add column for temporary training data

Revision ID: 7a6f90e4d7c7
Revises: f368d12fda0c
Create Date: 2021-12-20 15:44:52.736132

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a6f90e4d7c7"
down_revision = "f368d12fda0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("tmp_train_pipeline", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "tmp_train_pipeline")
    # ### end Alembic commands ###
