"""Add default model for comparison

Revision ID: c55153610b2f
Revises: 7a6f90e4d7c7
Create Date: 2021-12-31 12:07:22.057243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c55153610b2f"
down_revision = "7a6f90e4d7c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("model_default", sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "model_default")
    # ### end Alembic commands ###
