"""Save the sklearn pipeline in the db

Revision ID: ede715e38fda
Revises: c55153610b2f
Create Date: 2022-01-11 12:21:09.571668

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ede715e38fda"
down_revision = "c55153610b2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("model_pipeline", sa.PickleType(), nullable=True)
    )
    op.add_column(
        "project", sa.Column("model_pipeline_default", sa.PickleType(), nullable=True)
    )
    op.drop_column("project", "model")
    op.drop_column("project", "model_default")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "model_default", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "project",
        sa.Column("model", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    op.drop_column("project", "model_pipeline_default")
    op.drop_column("project", "model_pipeline")
    # ### end Alembic commands ###
